### ISSUE TITLE
PAML building Components as child classes?

### ISSUE THREAD

**Issue by jakebeal** [SD2E/paml#2]
I found this in a serialization:

```
<https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/PrimitiveExecutable5/LocalValuePin2/Component4> a sbol:Component ;
    sbol:displayId "Component4" ;
    sbol:name "LUDOX(R) CL-X colloidal silica, 45 wt. % suspension in H2O" ;
    sbol:type <https://identifiers.org/pubchem.substance:24866361> .
```

This seems to indicate that the OPIL library being used by PAML has built an sbol:Component as a child object rather than a TopLevel. This was produced by https://github.com/SD2E/paml/blob/main/scratch.py

**Comment by bbartley** [comment]
The assignment in this line https://github.com/SD2E/paml/blob/main/scratch.py#L91 is where the parent-child relationship of this object is created.  I believe this happens because the `material` property is defined as a compositional property here https://github.com/SD2E/paml/blob/main/paml/paml.ttl#L301

**Comment by jakebeal** [comment]
This has been fixed.
